language: node_js
node_js:
  - "0.12"

addons:
  firefox: "39.0"

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - npm install selenium-standalone@latest -g
  - selenium-standalone install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - selenium-standalone start &
  - sleep 3 # give selenium some time to start
  